# site settings
title: Stuti Foods
subtitle:
email: stutifoods.ecs@gmail.com
description: Khakhra & Namkeen | ખાખરા અને નમકીન 
baseurl: # "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 2-3-4 Denap Estate, Behind Navjivan Hyundai Service Center, Opp Khatodra Police Chowki, Udhna
city: Surat
state: GJ
zip_code: 395002
country: India
phone: +91 982 512 8761

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
